source "https://rubygems.org"

gem "rails", "4.2.0"
gem "sqlite3"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "haml", "~> 4.0.5"
gem "sidekiq"
gem "rest-client"
gem "google-api-client"
gem "pg", "~> 0.17.1"
gem "newrelic_rpm"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "better_errors"
  gem "binding_of_caller"
  gem "annotate"
end

gem "unicorn"
gem "capistrano", "~> 3.1.0"
gem "capistrano-rvm"
gem "capistrano-rails", "~> 1.1"
gem "capistrano-bundler"
gem "capistrano-sidekiq"
